# Generated by Django 4.2 on 2023-06-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_rename_status_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignee',
            name='picture',
            field=models.ImageField(default='default.png', upload_to='images/'),
        ),
    ]
