# Generated by Django 4.2 on 2023-06-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_assignee_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='description',
            field=models.CharField(default='default description', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignee',
            name='picture',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
