# Generated by Django 4.2 on 2023-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_board_description_alter_assignee_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('W', 'write'), ('R', 'read')], max_length=50)),
                ('assignee', models.ManyToManyField(to='tasks.assignee')),
            ],
        ),
    ]
